- title: K8s Architecture
  url: https://kubernetes.io/docs/concepts/architecture/nodes/
  divs_in: 
    - class: "td-content"
    - id: "content"
  divs_out: 
    - id: "what-s-next"
    - id: "pre-footer"
    - class: "feedback--link"
 
    #https://fonseca.de.com
