- title: K8s Architecture
  url: https://kubernetes.io/docs/concepts/architecture/nodes/
  divs_in: 
    - class: "td-content"
    - id: "content"
  divs_out: 
    - class: "pre-footer"
 
    #https://fonseca.de.com
